# Generated by Django 5.0.7 on 2024-07-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emp',
            table='empp',
        ),
    ]
