# Generated by Django 5.0.4 on 2024-08-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Img',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
